### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by gmnsnr** [gmnsnr/BBM487-20142-14#2]
Classes  ,attributes and relationshipsDomain analizlerini gerçekleştirip  bu domainlere bağlı sınıfları , sınıfların sahip oldukları özellikleri aralarındaki ilişkileri UML Class Diyagramı şeklinde modelleyip tarafıma gönderiniz

**Comment by brkens** [comment]
Paydaşların yetkilerinin ve özelliklerinin analizi yapıldı. Bu alanla ilgili class'lar ve ilişkiler UML Class Diyagram kullanılarak hazırlandı ve teslim edildi.
