### ISSUE TITLE
Use case Diagrams

### ISSUE THREAD

**Issue by gmnsnr** [gmnsnr/BBM487-20142-14#4]
Use-case diyagramlarının oluşturulması ve oluşturulan use-caselere özet halinde use-case senaryolarının yazılması

**Comment by gkucar** [comment]
![akademik-ogrenci](https://cloud.githubusercontent.com/assets/6156122/6624894/0cbc510a-c8f5-11e4-8734-79dc001a81e1.jpg)
![ogrenci](https://cloud.githubusercontent.com/assets/6156122/6624895/0cbdfd52-c8f5-11e4-9efa-7c88aa4a75e7.jpg)

**Comment by gkucar** [comment]
Use case diagramları oluşturuldu,  özet senaryoları yazıldı ve proje yöneticisine gönderildi.
